version: "3.5"
services:
  # NOTE: Rubbish for non-time-series, but left in for posterity
  grafana:
    container_name: grafana
    image: "grafana/grafana-oss:9.5.12"
    restart: unless-stopped
    volumes:
      # NOTE: This won't work unless you do `sudo chown 472:472 data/grafana`
      - "./data/grafana:/var/lib/grafana"
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=ethercrab
      - GF_SECURITY_ADMIN_PASSWORD=ethercrab
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true

  postgres:
    container_name: postgres
    image: postgres:16.0-alpine
    restart: always
    volumes:
      - "./data/postgres/data:/var/lib/postgresql/data/pgdata"
      # Data dir must be empty for these scripts to run
      - "./data/pg-init:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ethercrab
      POSTGRES_PASSWORD: ethercrab
      POSTGRES_DB: ethercrab
      PGDATA: /var/lib/postgresql/data/pgdata
      # INSECURE. LOCAL USE ONLY. Added because Apache Zeppelin is rubbish and doesn't understand
      # newer auth methods.
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    links:
      - "postgres:postgres"
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  zeppelin:
    container_name: zeppelin
    build: ./zeppelin
    links:
      - "postgres:postgres"
    ports:
      - 8081:8080
    environment:
      ZEPPELIN_LOG_DIR: /logs
      ZEPPELIN_NOTEBOOK_DIR: /notebook
      ZEPPELIN_INTERPRETER_OUTPUT_LIMIT: 2048000
    volumes:
      - "./data/zeppelin/logs:/logs"
      - "./data/zeppelin/notebook:/notebook"
